- name: update
  become: true
  become_user: root
  lineinfile:
    state: present
    path: /etc/sysctl.conf
    regexp: '^{{item}}'
    line: "{{item}}"
  with_items:
  - "net.ipv6.conf.all.disable_ipv6=1"
  - "net.ipv6.conf.default.disable_ipv6=1"
  - "net.ipv6.conf.lo.disable_ipv6=1"

- name: set ipv6 settings
  shell: "sudo sysctl -p"

- name: check ipv6 settings
  shell: "cat /proc/sys/net/ipv6/conf/all/disable_ipv6"
  register: out
  failed_when: out.stdout != '1'